const {authUser,req:sbreq,json,profile}=require('./_lib');
const esc=v=>encodeURIComponent(String(v));
async function guard(req,res){const u=await authUser(req);if(!u){json(res,401,{error:'Login required'});return null}const p=await profile(u.id);if(p?.role!=='admin'){json(res,403,{error:'Admin only'});return null}return u}
async function audit(adminId,action,details){try{await sbreq('/rest/v1/admin_audit_logs',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({admin_id:adminId,action,details})})}catch(e){}}
async function rankAstrologers(){
 const [as,convs,reviews]=await Promise.all([
  sbreq('/rest/v1/astrologers?select=id,verified,online,rank_score&limit=1000'),
  sbreq('/rest/v1/conversations?select=id,astrologer_id,status,astrologer_response_seconds&limit=5000'),
  sbreq('/rest/v1/reviews?select=astrologer_id,rating,moderation_status&limit=5000')
 ]);
 const arr=as.map(a=>{
  const cs=convs.filter(c=>c.astrologer_id===a.id); const completed=cs.filter(c=>c.status==='closed').length; const attempts=cs.filter(c=>['accepted','closed','missed','rejected','astrologer_accepted'].includes(c.status)).length; const accepted=cs.filter(c=>['accepted','closed'].includes(c.status)).length; const missed=cs.filter(c=>c.missed_by==='astrologer').length; const rs=reviews.filter(r=>r.astrologer_id===a.id&&r.moderation_status!=='hidden'); const avg=rs.length?rs.reduce((s,r)=>s+Number(r.rating||0),0)/rs.length:0; const responses=cs.map(c=>Number(c.astrologer_response_seconds)).filter(n=>Number.isFinite(n)&&n>=0); const avgResp=responses.length?responses.reduce((s,n)=>s+n,0)/responses.length:120; const rating=avg/5; const completion=attempts?completed/attempts:0; const acceptance=attempts?accepted/attempts:0; const response=Math.max(0,1-Math.min(avgResp,120)/120); const reliability=attempts?Math.max(0,1-missed/attempts):0; const score=Math.round((rating*.35+completion*.20+acceptance*.20+response*.15+reliability*.10)*10000)/100; return {...a,rank_score:score,rating_avg:Math.round(avg*100)/100,completed_chats:completed,accepted_requests:accepted,missed_requests:missed,response_seconds_avg:Math.round(avgResp*100)/100}
 });
 arr.sort((x,y)=>y.rank_score-x.rank_score||y.rating_avg-x.rating_avg); for(let i=0;i<arr.length;i++){const a=arr[i];await sbreq(`/rest/v1/astrologers?id=eq.${esc(a.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({rank_score:a.rank_score,rank_position:i+1,rating_avg:a.rating_avg,completed_chats:a.completed_chats,accepted_requests:a.accepted_requests,missed_requests:a.missed_requests,response_seconds_avg:a.response_seconds_avg})})} return arr;
}
module.exports=async(req,res)=>{try{
 const u=await guard(req,res);if(!u)return; const action=String(req.query?.action||'overview');
 if(req.method==='GET'&&action==='overview'){const [profiles,apps,astros,convs,reviews,kundalis,payments]=await Promise.all([sbreq('/rest/v1/profiles?select=id,role,blocked&limit=5000'),sbreq('/rest/v1/astrologer_applications?select=id,status&limit=5000'),sbreq('/rest/v1/astrologers?select=id,verified,online&limit=5000'),sbreq('/rest/v1/conversations?select=id,status&limit=5000'),sbreq('/rest/v1/reviews?select=id,rating,moderation_status&limit=5000'),sbreq('/rest/v1/kundalis?select=id&limit=5000'),sbreq('/rest/v1/payments?select=id,status,amount&limit=5000')]);return json(res,200,{stats:{users:profiles.filter(x=>x.role==='user').length,astrologers:profiles.filter(x=>x.role==='astrologer').length,admins:profiles.filter(x=>x.role==='admin').length,blockedUsers:profiles.filter(x=>x.blocked).length,pendingApplications:apps.filter(x=>x.status==='pending').length,approvedAstrologers:astros.filter(x=>x.verified).length,onlineAstrologers:astros.filter(x=>x.online&&x.last_seen&&(Date.now()-new Date(x.last_seen).getTime()<=75000)).length,activeChats:convs.filter(x=>x.status==='accepted').length,totalChats:convs.length,totalReviews:reviews.length,pendingReviews:reviews.filter(x=>x.moderation_status==='pending').length,totalKundalis:kundalis.length,pendingPayments:payments.filter(x=>x.status==='pending').length,approvedPayments:payments.filter(x=>x.status==='approved').length,revenue:payments.filter(x=>x.status==='approved').reduce((s,x)=>s+Number(x.amount||0),0),pendingAmount:payments.filter(x=>x.status==='pending').reduce((s,x)=>s+Number(x.amount||0),0),refundedAmount:payments.filter(x=>x.status==='refunded').reduce((s,x)=>s+Number(x.amount||0),0),astrologerPayable:payments.filter(x=>x.status==='approved').reduce((s,x)=>s+Number(x.amount||0),0)}})}
 if(req.method==='GET'&&action==='users'){const q=String(req.query?.q||'').trim();let path='/rest/v1/profiles?select=id,full_name,email,phone,role,blocked,blocked_reason,created_at,updated_at&order=created_at.desc&limit=500';if(q)path+=`&or=(full_name.ilike.*${esc(q)}*,email.ilike.*${esc(q)}*,phone.ilike.*${esc(q)}*)`;return json(res,200,{users:await sbreq(path)})}
 if(req.method==='GET'&&action==='applications'){return json(res,200,{applications:await sbreq('/rest/v1/astrologer_applications?select=*,profile:profiles!astrologer_applications_user_id_fkey(id,full_name,email,phone,role,blocked)&order=created_at.desc&limit=500')})}
 if(req.method==='GET'&&action==='astrologers'){const ranked=await rankAstrologers();return json(res,200,{astrologers:ranked})}
 if(req.method==='GET'&&action==='conversations'){return json(res,200,{conversations:await sbreq('/rest/v1/conversations?select=*,user:profiles!conversations_user_id_fkey(id,full_name,email),astrologer:profiles!conversations_astrologer_id_fkey(id,full_name,email),admin:profiles!conversations_admin_id_fkey(id,full_name,email)&order=created_at.desc&limit=500')})}
 if(req.method==='GET'&&action==='reviews'){return json(res,200,{reviews:await sbreq('/rest/v1/reviews?select=*,user:profiles!reviews_user_id_fkey(id,full_name,email),astrologer:profiles!reviews_astrologer_id_fkey(id,full_name,email)&order=created_at.desc&limit=500')})}
 if(req.method==='GET'&&action==='payments'){return json(res,200,{payments:await sbreq('/rest/v1/payments?select=*,user:profiles!payments_user_id_fkey(id,full_name,email),astrologer:profiles!payments_astrologer_id_fkey(id,full_name)&order=created_at.desc&limit=500')})}
 if(req.method==='GET'&&action==='audit'){return json(res,200,{logs:await sbreq('/rest/v1/admin_audit_logs?select=*,admin:profiles!admin_audit_logs_admin_id_fkey(full_name,email)&order=created_at.desc&limit=300')})}
 if(req.method==='GET'&&action==='messages'){const id=String(req.query?.conversation_id||'');if(!id)return json(res,400,{error:'conversation_id required'});return json(res,200,{messages:await sbreq(`/rest/v1/messages?conversation_id=eq.${esc(id)}&select=*,sender:profiles!messages_sender_id_fkey(full_name,role)&order=created_at.asc&limit=1000`)})}
 if(req.method==='POST'&&action==='recalculate-ranks'){const a=await rankAstrologers();await audit(u.id,'recalculate_ranks',{count:a.length});return json(res,200,{astrologers:a})}
 if(req.method==='PATCH'){
  const b=req.body||{};
  if(action==='user'){const id=String(b.user_id||'');if(!id)return json(res,400,{error:'user_id required'});const patch={};if(['user','astrologer','admin'].includes(b.role))patch.role=b.role;if('full_name'in b)patch.full_name=String(b.full_name||'');if('phone'in b)patch.phone=String(b.phone||'');if('blocked'in b){patch.blocked=!!b.blocked;patch.blocked_reason=String(b.blocked_reason||'');patch.blocked_at=b.blocked?new Date().toISOString():null}const rows=await sbreq(`/rest/v1/profiles?id=eq.${esc(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});await audit(u.id,b.blocked?'block_user':'user_update',{user_id:id,changes:patch});return json(res,200,{user:rows[0]||null})}
  if(action==='application'){const userId=String(b.user_id||'').trim();if(!userId)return json(res,400,{error:'user_id required'});const status=String(b.status||'').trim();if(!['approved','rejected'].includes(status))return json(res,400,{error:'Invalid status'});const a=(await sbreq(`/rest/v1/astrologer_applications?user_id=eq.${esc(userId)}&select=*`))[0];if(!a)return json(res,404,{error:'Application not found'});const now=new Date().toISOString();if(status==='approved'){
   // Promote the account first. Service-role REST is used here so admin approval is not blocked by client RLS.
   await sbreq(`/rest/v1/profiles?id=eq.${esc(userId)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({role:'astrologer',blocked:false,avatar_url:a.avatar_url||null,updated_at:now})});
   const astro={id:userId,bio:a.bio||'',experience_years:Number(a.experience_years||0),expertise:Array.isArray(a.expertise)?a.expertise:[],languages:Array.isArray(a.languages)?a.languages:[],fee:Number(a.requested_fee||0),discount:0,online:false,verified:true,approved_at:now};
   if(a.education!==undefined)astro.education=a.education||'';
   if(a.avatar_url!==undefined)astro.avatar_url=a.avatar_url||null;
   try{await sbreq('/rest/v1/astrologers',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(astro)})}
   catch(e){
     // Older deployments may not yet have the additive education/avatar columns. Retry with core columns so approval still works.
     if(/education|avatar_url|column/i.test(String(e.message||''))){delete astro.education;delete astro.avatar_url;await sbreq('/rest/v1/astrologers',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(astro)})}else throw e;
   }
 }
 const rows=await sbreq(`/rest/v1/astrologer_applications?id=eq.${esc(a.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status,admin_note:String(b.admin_note||''),updated_at:now})});
 if(!rows[0]||rows[0].status!==status)throw new Error('Approval status could not be saved');
 await audit(u.id,'application_'+status,{application_id:a.id,user_id:userId});
 return json(res,200,{ok:true,application:rows[0]})}
  if(action==='astrologer'){const id=String(b.astrologer_id||'');if(!id)return json(res,400,{error:'astrologer_id required'});const patch={};for(const k of ['bio','experience_years','expertise','languages','online','verified'])if(k in b)patch[k]=b[k];if('fee'in b)patch.fee=Math.max(0,Number(b.fee)||0);if('discount'in b)patch.discount=Math.min(100,Math.max(0,Number(b.discount)||0));if(b.verified===true)patch.approved_at=new Date().toISOString();const rows=await sbreq(`/rest/v1/astrologers?id=eq.${esc(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});await audit(u.id,'astrologer_update',{astrologer_id:id,changes:patch});return json(res,200,{astrologer:rows[0]})}
  if(action==='payment'){const id=String(b.payment_id||'');if(!id)return json(res,400,{error:'payment_id required'});const status=['approved','rejected','refunded','pending'].includes(b.status)?b.status:null;if(!status)return json(res,400,{error:'Invalid payment status'});const patch={status,admin_note:String(b.admin_note||''),updated_at:new Date().toISOString()};if(status==='approved'){patch.approved_by=u.id;patch.approved_at=new Date().toISOString()}const rows=await sbreq(`/rest/v1/payments?id=eq.${esc(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});await audit(u.id,'payment_'+status,{payment_id:id});return json(res,200,{payment:rows[0]})}
  if(action==='review'){const id=String(b.review_id||'');const status=['pending','approved','hidden','flagged'].includes(b.moderation_status)?b.moderation_status:'pending';const rows=await sbreq(`/rest/v1/reviews?id=eq.${esc(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({moderation_status:status,admin_note:String(b.admin_note||'')})});await audit(u.id,'review_moderation',{review_id:id,status});return json(res,200,{review:rows[0]})}
  if(action==='conversation'){const id=String(b.conversation_id||'');const status=['requested','astrologer_accepted','accepted','rejected','missed','closed'].includes(b.status)?b.status:null;if(!status)return json(res,400,{error:'Invalid status'});const patch={status};if(status==='closed')patch.closed_at=new Date().toISOString();const rows=await sbreq(`/rest/v1/conversations?id=eq.${esc(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});await audit(u.id,'conversation_update',{conversation_id:id,status});return json(res,200,{conversation:rows[0]})}
 }
 return json(res,405,{error:'Method not allowed'});
}catch(e){return json(res,500,{error:e.message})}};
