const { calculateEphemeris } = require("./ephemeris-provider");
const SIGNS=["Mesha","Vrishabha","Mithuna","Karka","Simha","Kanya","Tula","Vrischika","Dhanu","Makara","Kumbha","Meena"];
const SIGN_EN=["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"];
const SIGN_LORD=["Mars","Venus","Mercury","Moon","Sun","Mercury","Venus","Mars","Jupiter","Saturn","Saturn","Jupiter"];
const NAK=["Ashwini","Bharani","Krittika","Rohini","Mrigashira","Ardra","Punarvasu","Pushya","Ashlesha","Magha","Purva Phalguni","Uttara Phalguni","Hasta","Chitra","Swati","Vishakha","Anuradha","Jyeshtha","Mula","Purva Ashadha","Uttara Ashadha","Shravana","Dhanishtha","Shatabhisha","Purva Bhadrapada","Uttara Bhadrapada","Revati"];
const LORDS=["Ketu","Venus","Sun","Moon","Mars","Rahu","Jupiter","Saturn","Mercury"];
const YEARS={Ketu:7,Venus:20,Sun:6,Moon:10,Mars:7,Rahu:18,Jupiter:16,Saturn:19,Mercury:17};
const PLANETS=["Sun","Moon","Mars","Mercury","Jupiter","Venus","Saturn","Rahu","Ketu"];
const norm=x=>((Number(x)%360)+360)%360;
const sign=x=>Math.floor(norm(x)/30)+1;
const relHouse=(fromSign,toSign)=>((toSign-fromSign+12)%12)+1;
function nakshatra(longitude){const span=360/27,q=norm(longitude)/span,index=Math.min(26,Math.floor(q)),f=q-index;return{name:NAK[index],index:index+1,pada:Math.min(4,Math.floor(f*4)+1),lord:LORDS[index%9],degreesInNakshatra:+(f*13.3333333333).toFixed(6)}}
function houseFromAsc(asc,longitude){return relHouse(sign(asc),sign(longitude))}
function navamsaSign(longitude){const s=sign(longitude)-1,part=Math.min(8,Math.floor((norm(longitude)%30)/(30/9))),mod=s%3,start=mod===0?s:mod===1?(s+8)%12:(s+4)%12;return((start+part)%12)+1}
function buildD1(asc,planets){const lagna=sign(asc),d1=Array.from({length:12},(_,i)=>{const s=((lagna-1+i)%12)+1;return{house:i+1,sign:s,signName:SIGNS[s-1],signEnglish:SIGN_EN[s-1],planets:[]}});for(const p of PLANETS)d1[planets[p].house-1].planets.push(p);return d1}
function buildD9(asc,planets){const lagna=navamsaSign(asc),d9=Array.from({length:12},(_,i)=>{const s=((lagna-1+i)%12)+1;return{house:i+1,sign:s,signName:SIGNS[s-1],signEnglish:SIGN_EN[s-1],planets:[]}});for(const p of PLANETS){const ds=planets[p].d9Sign;const h=relHouse(lagna,ds);d9[h-1].planets.push(p)}return d9}
function addYears(date,years){return new Date(date.getTime()+Number(years)*365.2425*86400000)}
function parseBirthDateTime(input){const [y,m,d]=String(input.dob).split('-').map(Number);const [hh,mm,ss]=String(input.time||'12:00').split(':').map(Number);const off=Number(input.timezone??input.tzOffset??5.5);return new Date(Date.UTC(y,m-1,d,hh||0,mm||0,ss||0)-off*3600000)}
function generateSubPeriods(start,totalYears,parentLord){const result=[];let cursor=new Date(start),orderStart=LORDS.indexOf(parentLord);for(let j=0;j<9;j++){const lord=LORDS[(orderStart+j)%9],years=totalYears*YEARS[lord]/120,end=addYears(cursor,years);result.push({lord,start:cursor.toISOString().slice(0,10),end:end.toISOString().slice(0,10),years});cursor=end}return result}
function dashas(moonLongitude,input){const birth=parseBirthDateTime(input),n=nakshatra(moonLongitude),lord=n.lord,span=360/27,elapsed=(norm(moonLongitude)%span)/span,balance=YEARS[lord]*(1-elapsed),maha=[];let cursor=new Date(birth),index=LORDS.indexOf(lord);for(let i=0;i<18;i++){const md=LORDS[(index+i)%9],years=i===0?balance:YEARS[md],end=addYears(cursor,years),ad=generateSubPeriods(cursor,years,md),pd=ad.flatMap(a=>generateSubPeriods(new Date(a.start+"T00:00:00Z"),a.years,a.lord).map(x=>({...x,antardasha:a.lord})));maha.push({lord:md,start:cursor.toISOString().slice(0,10),end:end.toISOString().slice(0,10),years,balanceAtBirth:i===0,antardasha:ad,pratyantardasha:pd});cursor=end}return{birthDate:input.dob,birthTime:input.time,startingLord:lord,balanceYears:+balance.toFixed(8),mahadasha:maha}}
function lordOf(house,lagna){const s=((lagna-1+house-1)%12)+1;return SIGN_LORD[s-1]}
function occupiedHouse(planets,p){return planets[p]?.house||0}
function conjunction(planets,a,b){return planets[a].sign===planets[b].sign}
function kendraFrom(h1,h2){return [1,4,7,10].includes(relHouse(h1,h2))}
function aspectHouses(planet,from,to){const diff=relHouse(from,to);if(diff===7)return true;if(planet==='Mars'&&[4,8].includes(diff))return true;if(planet==='Jupiter'&&[5,9].includes(diff))return true;if(planet==='Saturn'&&[3,10].includes(diff))return true;return false}
function yogaRules(planets,lagna){const yogas=[],doshas=[],addY=(name,basis,strength='Rule match')=>yogas.push({name,basis,status:'Detected',strength}),addD=(name,basis,severity='Context dependent')=>doshas.push({name,basis,status:'Rule match',severity});
  if(conjunction(planets,'Sun','Mercury')) addY('Budhaditya Yoga','Sun and Mercury occupy the same sign. Classical strength depends on combustion, dignity and house context.');
  if(kendraFrom(planets.Moon.sign,planets.Jupiter.sign)) addY('Gajakesari Yoga','Jupiter is in a kendra (1/4/7/10) from the Moon.');
  if(conjunction(planets,'Moon','Mars')) addY('Chandra-Mangala Yoga','Moon and Mars occupy the same sign.');
  if(occupiedHouse(planets,'Mercury')===1||occupiedHouse(planets,'Mercury')===4||occupiedHouse(planets,'Mercury')===7||occupiedHouse(planets,'Mercury')===10){if([1,4,7,10].includes(planets.Mercury.house)&&[3,6].includes(planets.Mercury.sign%3+1)){} }
  const maha=[['Mars','Ruchaka', [1,4,7,10],[1,8]],['Mercury','Bhadra',[1,4,7,10],[3,6]],['Jupiter','Hamsa',[1,4,7,10],[4,9]],['Venus','Malavya',[1,4,7,10],[2,7]],['Saturn','Sasa',[1,4,7,10],[10,11]]];
  for(const [p,name,hs,ss] of maha) if(hs.includes(planets[p].house)&&ss.includes(planets[p].sign)) addY(name+' Mahapurusha Yoga',`${p} is in a kendra and in its own/exaltation sign under the configured Parashari screening rule.`);
  const ninth=lordOf(9,lagna),tenth=lordOf(10,lagna); if(planets[ninth]&&planets[tenth]&&(planets[ninth].sign===planets[tenth].sign||aspectHouses(ninth,planets[ninth].house,planets[tenth].house)||aspectHouses(tenth,planets[tenth].house,planets[ninth].house))) addY('Dharma-Karmadhipati Yoga',`9th lord ${ninth} and 10th lord ${tenth} are connected by conjunction/aspect under the configured rule.`);
  const second=lordOf(2,lagna),fifth=lordOf(5,lagna),ninthLord=lordOf(9,lagna); if([second,fifth,ninthLord].some(p=>planets[p]&&[1,2,5,9,11].includes(planets[p].house))) addY('Dhana Yoga Screening',`A wealth-house lord (2/5/9) occupies a configured wealth-supporting house.`);
  if([1,4,7,8,12].includes(planets.Mars.house)||[1,4,7,8,12].includes(relHouse(planets.Moon.sign,planets.Mars.sign))||[1,4,7,8,12].includes(relHouse(planets.Venus.sign,planets.Mars.sign))) addD('Mangal Dosha','Mars occupies a configured Manglik house from Lagna/Moon/Venus screening.','Cancellation and partner comparison required');
  if(conjunction(planets,'Sun','Rahu')||conjunction(planets,'Sun','Ketu')) addD('Surya Grahan Dosha','Sun is conjunct a lunar node.');
  if(conjunction(planets,'Moon','Rahu')||conjunction(planets,'Moon','Ketu')) addD('Chandra Grahan Dosha','Moon is conjunct a lunar node.');
  const malefics=['Sun','Mars','Saturn','Rahu','Ketu']; if(malefics.some(p=>conjunction(planets,'Moon',p))) addD('Papakartari/Chandra Affliction Screening','Moon is conjunct a configured natural malefic; full Papakartari requires adjacent-house checks.');
  if(planets.Mars.sign===4) addD('Mars Debilitation','Mars is in Cancer, its traditional debilitation sign.');
  if(planets.Saturn.sign===1) addD('Saturn Debilitation','Saturn is in Aries, its traditional debilitation sign.');
  if(planets.Jupiter.sign===10) addD('Jupiter Debilitation','Jupiter is in Capricorn, its traditional debilitation sign.');
  if(planets.Venus.sign===6) addD('Venus Debilitation','Venus is in Virgo, its traditional debilitation sign.');
  return{yogas,doshas,ruleSummary:{yogaRulesChecked:10,doshaRulesChecked:9}};
}

const SIGN_HI=["मेष","वृषभ","मिथुन","कर्क","सिंह","कन्या","तुला","वृश्चिक","धनु","मकर","कुंभ","मीन"];
const NAK_HI=["अश्विनी","भरणी","कृत्तिका","रोहिणी","मृगशिरा","आर्द्रा","पुनर्वसु","पुष्य","आश्लेषा","मघा","पूर्वाफाल्गुनी","उत्तराफाल्गुनी","हस्त","चित्रा","स्वाती","विशाखा","अनुराधा","ज्येष्ठा","मूल","पूर्वाषाढ़ा","उत्तराषाढ़ा","श्रवण","धनिष्ठा","शतभिषा","पूर्वाभाद्रपद","उत्तराभाद्रपद","रेवती"];
const TITHI_HI=["प्रतिपदा","द्वितीया","तृतीया","चतुर्थी","पंचमी","षष्ठी","सप्तमी","अष्टमी","नवमी","दशमी","एकादशी","द्वादशी","त्रयोदशी","चतुर्दशी"];
const YOGA_HI=["विष्कम्भ","प्रीति","आयुष्मान","सौभाग्य","शोभन","अतिगण्ड","सुकर्मा","धृति","शूल","गण्ड","वृद्धि","ध्रुव","व्याघात","हर्षण","वज्र","सिद्धि","व्यतीपात","वरीयान","परिघ","शिव","सिद्ध","साध्य","शुभ","शुक्ल","ब्रह्म","इन्द्र","वैधृति"];
const KARANA_MOVING=["बव","बालव","कौलव","तैतिल","गर","वणिज","विष्टि"];
const NAK_NADI=["आदि","मध्य","अन्त्य"];
const NAK_GANA={
  Ashwini:"देव",Bharani:"मनुष्य",Krittika:"राक्षस",Rohini:"मनुष्य",Mrigashira:"देव",Ardra:"मनुष्य",Punarvasu:"देव",Pushya:"देव",Ashlesha:"राक्षस",Magha:"राक्षस",["Purva Phalguni"]:"मनुष्य",["Uttara Phalguni"]:"मनुष्य",Hasta:"देव",Chitra:"राक्षस",Swati:"देव",Vishakha:"राक्षस",Anuradha:"देव",Jyeshtha:"राक्षस",Mula:"राक्षस",["Purva Ashadha"]:"मनुष्य",["Uttara Ashadha"]:"मनुष्य",Shravana:"देव",Dhanishtha:"मनुष्य",Shatabhisha:"राक्षस",["Purva Bhadrapada"]:"मनुष्य",["Uttara Bhadrapada"]:"मनुष्य",Revati:"देव"
};
const NAK_YONI={Ashwini:"अश्व",Bharani:"गज",Krittika:"मेष",Rohini:"सर्प",Mrigashira:"सर्प",Ardra:"श्वान",Punarvasu:"मार्जार",Pushya:"मेष",Ashlesha:"मार्जार",Magha:"मूषक",["Purva Phalguni"]:"मूषक",["Uttara Phalguni"]:"गो",Hasta:"महिष",Swati:"महिष",Chitra:"व्याघ्र",Vishakha:"व्याघ्र",Anuradha:"मृग",Jyeshtha:"मृग",Mula:"श्वान",["Purva Ashadha"]:"वानर",Shravana:"वानर",Dhanishtha:"सिंह",["Purva Bhadrapada"]:"सिंह",["Uttara Bhadrapada"]:"गो",["Uttara Ashadha"]:"नकुल",Shatabhisha:"अश्व",Revati:"गज"
};
const PAYA_BY_NAK={
  "Ardra":"रजत (चाँदी)","Punarvasu":"रजत (चाँदी)","Pushya":"रजत (चाँदी)","Ashlesha":"रजत (चाँदी)","Magha":"रजत (चाँदी)","Purva Phalguni":"रजत (चाँदी)","Uttara Phalguni":"रजत (चाँदी)","Hasta":"रजत (चाँदी)","Chitra":"रजत (चाँदी)","Swati":"रजत (चाँदी)","Vishakha":"रजत (चाँदी)","Anuradha":"रजत (चाँदी)",
  "Jyeshtha":"ताम्र (ताँबा)","Mula":"ताम्र (ताँबा)","Purva Ashadha":"ताम्र (ताँबा)","Uttara Ashadha":"ताम्र (ताँबा)","Shravana":"ताम्र (ताँबा)","Dhanishtha":"ताम्र (ताँबा)","Shatabhisha":"ताम्र (ताँबा)","Purva Bhadrapada":"ताम्र (ताँबा)","Uttara Bhadrapada":"ताम्र (ताँबा)",
  "Revati":"स्वर्ण (सोना)","Ashwini":"स्वर्ण (सोना)","Bharani":"स्वर्ण (सोना)",
  "Krittika":"लोह (लोहा)","Rohini":"लोह (लोहा)","Mrigashira":"लोह (लोहा)"
};
function weekdayHi(y,m,d){return ["रविवार","सोमवार","मंगलवार","बुधवार","गुरुवार","शुक्रवार","शनिवार"][new Date(Date.UTC(y,m-1,d)).getUTCDay()]}
function degToDms(x){const a=Math.abs(Number(x)||0),d=Math.floor(a),mf=(a-d)*60,m=Math.floor(mf),s=Math.round((mf-m)*60);return `${String(d).padStart(2,"0")}° ${String(m).padStart(2,"0")}′ ${String(s%60).padStart(2,"0")}″`}
function degreeInSign(longitude){const x=norm(Number(longitude)||0)%30;return +x.toFixed(6)}
function clockParts(totalMinutes){let t=((Number(totalMinutes)||0)%1440+1440)%1440,h=Math.floor(t/60),m=Math.floor(t%60),s=Math.round((t-Math.floor(t))*60);if(s===60){s=0;m++;}if(m===60){m=0;h=(h+1)%24;}return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
function noaaSunTimes(y,m,d,lat,lon,tz){
  const N=Math.floor((Date.UTC(y,m-1,d)-Date.UTC(y,0,0))/86400000);
  const gamma=2*Math.PI/365*(N-1),eq=229.18*(0.000075+0.001868*Math.cos(gamma)-0.032077*Math.sin(gamma)-0.014615*Math.cos(2*gamma)-0.040849*Math.sin(2*gamma));
  const dec=0.006918-0.399912*Math.cos(gamma)+0.070257*Math.sin(gamma)-0.006758*Math.cos(2*gamma)+0.000907*Math.sin(2*gamma)-0.002697*Math.cos(3*gamma)+0.00148*Math.sin(3*gamma);
  const phi=Number(lat)*Math.PI/180, zen=90.833*Math.PI/180, cosH=(Math.cos(zen)/(Math.cos(phi)*Math.cos(dec))-Math.tan(phi)*Math.tan(dec));
  if(cosH<=-1||cosH>=1)return{sunrise:null,sunset:null,equationOfTime:Math.round(eq*100)/100};
  const H=Math.acos(cosH)*180/Math.PI, solarNoon=720-4*Number(lon)-eq+60*Number(tz||0);
  return{sunrise:clockParts(solarNoon-H*4),sunset:clockParts(solarNoon+H*4),equationOfTime:Math.round(eq*100)/100};
}
function clockToMinutes(s){const a=String(s||"00:00:00").split(":").map(Number);return (a[0]||0)*60+(a[1]||0)+(a[2]||0)/60}
function ishtakal(localTime,sunrise){let diff=clockToMinutes(localTime)-clockToMinutes(sunrise);if(diff<0)diff+=1440;const gh=Math.floor(diff/24),rem=diff-gh*24,vg=Math.floor(rem/0.4),pal=Math.round((rem-vg*0.4)/0.0066666667);return `${String(gh).padStart(3,"0")}-${String(vg).padStart(2,"0")}-${String(pal%60).padStart(2,"0")}`}
function varnaForSign(s){return [1,5,9].includes(s)?"क्षत्रिय":[2,6,10].includes(s)?"वैश्य":[3,7,11].includes(s)?"शूद्र":"ब्राह्मण"}
function vashyaForSign(s){if([1,2,9,10].includes(s))return s===9||s===10?"वनचर/चतुष्पद":"चतुष्पद";if([4,12].includes(s))return"जलचर";if(s===5)return"वनचर";if(s===8)return"कीट";return"मानव"}
function navamshaName(p){return SIGN_HI[p.d9Sign-1]}
function dateDigits(s){return String(s||"").replace(/\D/g,"").split("").reduce((a,b)=>a+Number(b),0)}
function reduceNumber(n){let x=Math.abs(Number(n)||0);while(x>9)x=String(x).split("").reduce((a,b)=>a+Number(b),0);return x||0}
function traditionalLuckyNumbers(birthNumber){const map={1:[1,2,3,9],2:[2,1,5],3:[3,1,2,9],4:[4,1,7],5:[5,1,3,7],6:[6,3,9],7:[7,2,1],8:[8,5,6],9:[9,3,6]};return map[birthNumber]||[]}
function shubhYears(birthNumber){return Array.from({length:6},(_,i)=>birthNumber+9*i).filter(x=>x>=1&&x<=90)}
function monthHi(m){return ["जनवरी","फरवरी","मार्च","अप्रैल","मई","जून","जुलाई","अगस्त","सितंबर","अक्टूबर","नवंबर","दिसंबर"][m-1]}
function praharFromTime(time){const h=Number(String(time).split(":")[0]||0);return h<6?4:h<12?1:h<18?2:3}
function luckyFromChart(lagna,moonSign,planets){const signs=[lagna,moonSign,planets.Jupiter?.sign,planets.Venus?.sign].filter(Boolean);return{luckySigns:[...new Set(signs)].map(x=>SIGN_HI[x-1]),luckyPlanets:[planets.Jupiter?.sign,planets.Mars?.sign,planets.Moon?.sign].filter(Boolean).map(x=>SIGN_LORD[x-1])}}
const GHATAK_BY_RASHI={
1:{masa:"कार्तिक",tithi:"नन्दा (1, 6, 11)",day:"रविवार",nakshatra:"मघा",yoga:"विष्कम्भ",karana:"बव",prahar:1,moonRashi:"मेष",lagna:"मेष / तुला"},
2:{masa:"मार्गशीर्ष",tithi:"पूर्णा (5, 10, 15)",day:"शनिवार",nakshatra:"हस्त",yoga:"सुकर्मा",karana:"शकुनि",prahar:4,moonRashi:"कन्या",lagna:"वृषभ / वृश्चिक"},
3:{masa:"आषाढ़",tithi:"भद्रा (2, 7, 12)",day:"सोमवार",nakshatra:"स्वाती",yoga:"परिघ",karana:"चतुष्पद",prahar:3,moonRashi:"कुंभ",lagna:"कर्क / मकर"},
4:{masa:"पौष",tithi:"भद्रा (2, 7, 12)",day:"बुधवार",nakshatra:"अनुराधा",yoga:"व्याघात",karana:"नाग",prahar:1,moonRashi:"सिंह",lagna:"तुला / मेष"},
5:{masa:"ज्येष्ठ",tithi:"जया (3, 8, 13)",day:"शनिवार",nakshatra:"मूल",yoga:"धृति",karana:"बव",prahar:1,moonRashi:"मकर",lagna:"मकर / कर्क"},
6:{masa:"भाद्रपद",tithi:"पूर्णा (5, 10, 15)",day:"शनिवार",nakshatra:"श्रवण",yoga:"शुभ",karana:"कौलव",prahar:1,moonRashi:"मिथुन",lagna:"मीन / कन्या"},
7:{masa:"माघ",tithi:"रिक्ता (4, 9, 14)",day:"गुरुवार",nakshatra:"शतभिषा",yoga:"शुक्ल",karana:"तैतिल",prahar:4,moonRashi:"धनु",lagna:"कन्या / मीन"},
8:{masa:"आश्विन",tithi:"नन्दा (1, 6, 11)",day:"शुक्रवार",nakshatra:"रेवती",yoga:"व्यतीपात",karana:"गर",prahar:1,moonRashi:"वृषभ",lagna:"वृश्चिक / वृषभ"},
9:{masa:"श्रावण",tithi:"जया (3, 8, 13)",day:"शुक्रवार",nakshatra:"भरणी",yoga:"वज्र",karana:"तैतिल",prahar:1,moonRashi:"मीन",lagna:"धनु / मिथुन"},
10:{masa:"वैशाख",tithi:"रिक्ता (4, 9, 14)",day:"मंगलवार",nakshatra:"रोहिणी",yoga:"वैधृति",karana:"शकुनि",prahar:4,moonRashi:"सिंह",lagna:"कुंभ / सिंह"},
11:{masa:"चैत्र",tithi:"जया (3, 8, 13)",day:"गुरुवार",nakshatra:"आर्द्रा",yoga:"गण्ड",karana:"वणिज",prahar:3,moonRashi:"धनु",lagna:"मिथुन / धनु"},
12:{masa:"फाल्गुन",tithi:"पूर्णा (5, 10, 15)",day:"शुक्रवार",nakshatra:"आश्लेषा",yoga:"वज्र",karana:"विष्टि",prahar:6,moonRashi:"कुंभ",lagna:"सिंह / कुंभ"}
};
const PLANET_METAL={Sun:"तांबा",Moon:"चाँदी",Mars:"ताँबा",Mercury:"कांसा",Jupiter:"सोना",Venus:"चाँदी",Saturn:"लोहा",Rahu:"लोहा",Ketu:"मिश्र धातु"};
const PLANET_STONE={Sun:"माणिक",Moon:"मोती",Mars:"मूंगा",Mercury:"पन्ना",Jupiter:"पुखराज",Venus:"हीरा",Saturn:"नीलम",Rahu:"गोमेद",Ketu:"लहसुनिया"};
const WEEKDAY_PLANET={"रविवार":"Sun","सोमवार":"Moon","मंगलवार":"Mars","बुधवार":"Mercury","गुरुवार":"Jupiter","शुक्रवार":"Venus","शनिवार":"Saturn"};

function numerologyProfile(name,dob,birthNumber,lifePath,lucky,luckySigns,birthLocal){
  const PY={A:1,B:2,C:3,D:4,E:5,F:6,G:7,H:8,I:9,J:1,K:2,L:3,M:4,N:5,O:6,P:7,Q:8,R:9,S:1,T:2,U:3,V:4,W:5,X:6,Y:7,Z:8};
  const CH={A:1,B:2,C:3,D:4,E:5,F:8,G:3,H:5,I:1,J:1,K:2,L:3,M:4,N:5,O:7,P:8,Q:1,R:2,S:3,T:4,U:6,V:6,W:6,X:5,Y:1,Z:7};
  const clean=String(name||'').toUpperCase().replace(/[^A-Z]/g,'');
  const digits=String(dob||'').replace(/\D/g,'');
  const day=Number(String(dob||'').split('-')[2]||0), month=Number(String(dob||'').split('-')[1]||0), year=new Date().getFullYear();
  const sum=(obj)=>[...clean].reduce((a,c)=>a+(obj[c]||0),0);
  const r=(n,master=true)=>{let x=Math.abs(Number(n)||0);while(x>9&&!(master&&[11,22,33].includes(x)))x=String(x).split('').reduce((a,b)=>a+Number(b),0);return x||0};
  const py=sum(PY), ch=sum(CH), vowels=[...clean].filter(c=>/[AEIOU]/.test(c)).reduce((a,c)=>a+(PY[c]||0),0), cons=[...clean].filter(c=>!/^[AEIOU]$/.test(c)).reduce((a,c)=>a+(PY[c]||0),0);
  const personalYear=r(day+month+String(year).split('').reduce((a,b)=>a+Number(b),0)), personalMonth=r(personalYear+month), personalDay=r(personalMonth+day);
  return {birthNumber,lifePath,luckyNumbers:lucky,unluckyNumbers:[4,8].filter(x=>x!==r(birthNumber,false)),luckyDays:['गुरुवार','मंगलवार'],luckyYears:shubhYears(birthNumber),luckySigns:luckySigns.luckySigns,luckyPlanets:luckySigns.luckyPlanets,month:monthHi(Number(String(dob||'').split('-')[1]||1)),prahar:praharFromTime(birthLocal),nameNumberChaldean:clean?r(ch):null,nameNumberPythagorean:clean?r(py):null,soulNumber:clean?r(vowels):null,personalityNumber:clean?r(cons):null,attitudeNumber:r(day+month),maturityNumber:clean?r(lifePath+r(py)):null,personalYear,personalMonth,personalDay,yearUsed:year,compound:{day:day||null,lifePathTotal:dateDigits(dob)||null,pythagoreanNameTotal:clean?py:null,chaldeanNameTotal:clean?ch:null},note:'पारंपरिक अंक-ज्योतिष आधारित सहायक विवरण; वैज्ञानिक माप या निश्चित भविष्यवाणी नहीं। नामांक के लिए English/Latin spelling उपयोग की जाती है।'};
}

function favorableDetails(lagna,moonSign,planets,birthNumber){
  const lagnaLord=SIGN_LORD[lagna-1], fifthLord=lordOf(5,lagna), ninthLord=lordOf(9,lagna), sixthLord=lordOf(6,lagna), eighthLord=lordOf(8,lagna), twelfthLord=lordOf(12,lagna);
  const goodPlanets=[lagnaLord,fifthLord,ninthLord].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i), evilPlanets=[sixthLord,eighthLord,twelfthLord].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i);
  const luckyDays=goodPlanets.map(x=>Object.entries(WEEKDAY_PLANET).find(([,p])=>p===x)?.[0]).filter(Boolean);
  const goodSigns=goodPlanets.map(x=>{const i=SIGN_LORD.indexOf(x);return SIGN_HI[i]||null}).filter(Boolean);
  const goodLagnas=[lagna,((lagna+4-1)%12)+1,((lagna+8-1)%12)+1].map(x=>SIGN_HI[x-1]);
  return{luckyNumber:birthNumber,goodNumbers:traditionalLuckyNumbers(birthNumber),evilNumbers:[4,5,8].filter(x=>x!==birthNumber),goodYears:shubhYears(birthNumber),luckyDays:[...new Set(luckyDays)],goodPlanets:[...new Set(goodPlanets)],evilPlanets:[...new Set(evilPlanets)],friendlySigns:[...new Set(goodSigns)],goodLagna:[...new Set(goodLagnas)],luckyMetal:PLANET_METAL[lagnaLord]||"—",luckyStone:PLANET_STONE[lagnaLord]||"—",basis:"लग्न स्वामी, पंचम/नवम स्वामी और जन्मांक पर आधारित पारंपरिक सहायक नियम"};
}
function birthDetails(input,provider,asc,lagna,planets){
  const [y,m,d]=String(input.dob).split("-").map(Number), [hh,mm,ss]=String(input.time||"12:00").split(":").map(Number), tz=Number(input.timezone??input.tzOffset??5.5), lon=Number(input.longitude), lat=Number(input.latitude);
  const moon=planets.Moon, sun=planets.Sun, sunTropical=norm(sun.longitude+Number(provider.ayanamsa||0)), elong=norm(moon.longitude-sun.longitude), tithiNo=Math.floor(elong/12)+1, paksha=tithiNo<=15?"शुक्ल":"कृष्ण", tithiIndex=(tithiNo-1)%15;
  const tithiName=tithiNo===15?(paksha==="शुक्ल"?"पूर्णिमा":"अमावस्या"):TITHI_HI[tithiIndex];
  const yogaNo=Math.floor(norm(moon.longitude+sun.longitude)/(360/27))+1;
  const halfIndex=Math.floor(elong/6); let karana;
  if(halfIndex===0)karana="किंस्तुघ्न"; else if(halfIndex>=57)karana=["शकुनि","चतुष्पद","नाग"][halfIndex-57]; else karana=KARANA_MOVING[(halfIndex-1)%7];
  const n=moon.nakshatra, nadi=NAK_NADI[(n.index-1)%3], gana=NAK_GANA[n.name]||"—", yoni=NAK_YONI[n.name]||"—", paya=PAYA_BY_NAK[n.name]||"—";
  const sunTimes=noaaSunTimes(y,m,d,lat,lon,tz), birthLocal=String(input.time||"12:00")+(String(input.time||"").split(":").length===2?":00":""), lmtCorrection=(lon-(tz*15))*4, lmt=clockParts(clockToMinutes(birthLocal)+lmtCorrection), utc=clockParts(clockToMinutes(birthLocal)-tz*60);
  const jd=Number(provider.julianDay||0), obliquity=23.439291-0.0130042*((jd-2451545)/36525), lifePath=reduceNumber(dateDigits(input.dob)), birthNumber=reduceNumber(d), lucky=traditionalLuckyNumbers(birthNumber), nakSpan=360/27, elapsed=(norm(moon.longitude)%nakSpan)/nakSpan, dashaBalanceYears=YEARS[n.lord]*(1-elapsed), dashaYears=Math.floor(dashaBalanceYears), dashaMonths=Math.floor((dashaBalanceYears-dashaYears)*12), dashaDays=Math.round((((dashaBalanceYears-dashaYears)*12)-dashaMonths)*30.4375), luckySigns=luckyFromChart(lagna,moon.sign,planets);
  const ascLord=SIGN_LORD[lagna-1], rashiLord=SIGN_LORD[moon.sign-1], favorable=favorableDetails(lagna,moon.sign,planets,birthNumber), ghatak=GHATAK_BY_RASHI[moon.sign]||null;
  return {person:{name:input.name||"",gender:input.gender||"",genderHi:{male:"पुरुष",female:"महिला",other:"अन्य"}[String(input.gender||"").toLowerCase()]||input.gender||"—",dob:input.dob,time:birthLocal,weekday:weekdayHi(y,m,d),place:input.place||"",latitude:lat,longitude:lon,timezone:tz},panchangAtBirth:{tithi:{number:tithiNo,name:tithiName,paksha},nakshatra:{name:n.name,nameHi:NAK_HI[n.index-1],pada:n.pada,lord:n.lord},nadi,gana,yoni,paya,varna:varnaForSign(moon.sign),vashya:vashyaForSign(moon.sign),yoga:{number:yogaNo,name:YOGA_HI[yogaNo-1]},karana},birthChart:{lagna:SIGNS[lagna-1],lagnaHi:SIGN_HI[lagna-1],lagnaLord:ascLord,rashi:SIGNS[moon.sign-1],rashiHi:SIGN_HI[moon.sign-1],rashiLord,nakshatra:n.name,nakshatraHi:NAK_HI[n.index-1],pada:n.pada,nakshatraLord:n.lord},dashaBhogya:{lord:n.lord,years:dashaYears,months:dashaMonths,days:dashaDays,totalYears:+dashaBalanceYears.toFixed(6),display:`${dashaYears} वर्ष ${dashaMonths} माह ${dashaDays} दिन`},timeDetails:{ishtakaal:sunTimes.sunrise?ishtakal(birthLocal,sunTimes.sunrise):null,localMeanTime:lmt,timezone:tz,gmtBirthTime:utc,julianDay:+jd.toFixed(5),localMeanTimeCorrection:`${lmtCorrection>=0?"+":""}${lmtCorrection.toFixed(2)} min`,equationOfTime:sunTimes.equationOfTime==null?null:`${sunTimes.equationOfTime.toFixed(2)} min`},astronomy:{ayanamsa:+Number(provider.ayanamsa||0).toFixed(6),ayanamsaName:"लाहिरी (Chitrapaksha)",obliquity:+obliquity.toFixed(6),sunSignHindu:SIGNS[sun.sign-1],sunSignHinduHi:SIGN_HI[sun.sign-1],sunSignWestern:SIGN_EN[Math.floor(sunTropical/30)],sunLongitudeTropical:+sunTropical.toFixed(6),sunrise:sunTimes.sunrise,sunset:sunTimes.sunset,dayDuration:(sunTimes.sunrise&&sunTimes.sunset)?clockParts(clockToMinutes(sunTimes.sunset)-clockToMinutes(sunTimes.sunrise)):null},numerology:numerologyProfile(input.name,input.dob,birthNumber,lifePath,lucky,luckySigns,birthLocal),favourablePoints:favorable,ghatak:ghatak,planetSummary:Object.fromEntries(PLANETS.map(p=>[p,{sign:planets[p].signName,signHi:SIGN_HI[planets[p].sign-1],house:planets[p].house,nakshatra:planets[p].nakshatra.name,pada:planets[p].nakshatra.pada,retrograde:planets[p].retrograde}]))};
}
function phalaDesh(data,planets,lagna){
  const moon=planets.Moon, sun=planets.Sun, jup=planets.Jupiter, sat=planets.Saturn, mars=planets.Mars, merc=planets.Mercury, venus=planets.Venus;
  const houseNames=["तनु/स्वभाव","धन/वाणी","सहज/पराक्रम","सुख/गृह","विद्या/संतान","रोग/ऋण/सेवा","विवाह/साझेदारी","आयु/परिवर्तन","धर्म/भाग्य","कर्म/करियर","लाभ/आय","व्यय/विदेश"];
  const h=(n)=>houseNames[n-1]||`भाव ${n}`;
  const lordHouse=(house)=>{const l=lordOf(house,lagna);return{lord:l,house:planets[l]?.house||null,sign:planets[l]?.sign||null}};
  const lagnaLord=planets[SIGN_LORD[lagna-1]], second=lordHouse(2), fourth=lordHouse(4), fifth=lordHouse(5), seventh=lordHouse(7), ninth=lordHouse(9), tenth=lordHouse(10), eleventh=lordHouse(11), sixth=lordHouse(6), eighth=lordHouse(8), twelfth=lordHouse(12);
  const items=[];
  const add=(title,text,signal="परंपरागत संकेत",factors=[])=>items.push({title,text,signal,factors});
  const houseStrength=(x)=>x&&[1,4,5,7,9,10,11].includes(x.house)?"सहायक भाव-संबंध":"मिश्र/परिश्रम वाला भाव-संबंध";
  const currentMd=(data.dasha?.mahadasha||[]).find(x=>{const now=new Date(),s=new Date(x.start+"T00:00:00Z"),e=new Date(x.end+"T00:00:00Z");return now>=s&&now<e;});
  const yogaNames=(data.yogas||[]).map(x=>x.name);
  const doshaNames=(data.doshas||[]).map(x=>x.name);
  const beneficHouses=[jup.house,venus.house,merc.house,moon.house].filter(Boolean);
  const kendraCount=[1,4,7,10].filter(hh=>beneficHouses.includes(hh)).length;
  const dusthanaCount=[6,8,12].filter(hh=>[sun,mars,sat,planets.Rahu,planets.Ketu].some(p=>p&&p.house===hh)).length;
  const relationshipNote=data.person?.genderHi?`जन्म विवरण में लिंग ${data.person.genderHi} दर्ज है; विवाह-फलादेश को दोनों कुंडलियों के मिलान के साथ पढ़ना अधिक उचित है।`:"विवाह-फलादेश को दोनों कुंडलियों के मिलान के साथ पढ़ना अधिक उचित है।";

  add("समग्र जीवन-चित्र",`${SIGN_HI[lagna-1]} लग्न, ${SIGN_HI[moon.sign-1]} चंद्र राशि और ${NAK_HI[moon.nakshatra.index-1]} नक्षत्र को आधार बनाकर यह कुंडली जीवन में व्यवहार, मनोवृत्ति और कर्म-दिशा के तीन प्रमुख स्तर दिखाती है। लग्न स्वामी ${SIGN_LORD[lagna-1]} भाव ${lagnaLord?.house||"—"} में है, चंद्रमा भाव ${moon.house} में और सूर्य भाव ${sun.house} में है। इसलिए व्यक्ति की बाहरी शैली, भावनात्मक प्रतिक्रिया और आत्मविश्वास/कर्तव्य-बोध को अलग-अलग देखकर फलादेश करना चाहिए। यह एक विषय-आधारित विस्तृत व्याख्या है; किसी घटना का निश्चित होना केवल एक योग या एक ग्रह से तय नहीं किया जाता।`,"लग्न + चंद्र राशि + प्रमुख भावों का संयुक्त पारंपरिक विश्लेषण",[`लग्न: ${SIGN_HI[lagna-1]}`,`चंद्र राशि: ${SIGN_HI[moon.sign-1]}`,`नक्षत्र: ${NAK_HI[moon.nakshatra.index-1]} पद ${moon.nakshatra.pada}`,`लग्न स्वामी: ${SIGN_LORD[lagna-1]} भाव ${lagnaLord?.house||"—"}`]);

  add("सामान्य व्यक्तित्व",`${SIGN_HI[lagna-1]} लग्न के कारण व्यवहार में ${lagna===1||lagna===5||lagna===9?"स्वतंत्रता, पहल और अपने निर्णय पर भरोसा":"व्यावहारिकता, परिस्थिति को समझकर कदम उठाने और परिणाम पर ध्यान देने"} की प्रवृत्ति परंपरागत रूप से देखी जाती है। चंद्रमा ${SIGN_HI[moon.sign-1]} में होने से भावनात्मक प्रतिक्रिया में ${[1,5,9].includes(moon.sign)?"आदर्श, आत्मविश्वास और स्पष्टता":"व्यवहारिक सोच, सुरक्षा की जरूरत और परिस्थितियों के अनुसार ढलने"} का रंग जुड़ता है। ${moon.nakshatra.name} नक्षत्र मन की शैली को और सूक्ष्म बनाता है। इसलिए यह कुंडली ऐसे व्यक्ति की ओर संकेत करती है जो अपने अनुभवों से सीखकर धीरे-धीरे अपनी कार्यशैली को अधिक प्रभावी बना सकता है।`,"लग्न, चंद्र राशि और जन्म नक्षत्र",[`लग्न स्वामी ${SIGN_LORD[lagna-1]} भाव ${lagnaLord?.house||"—"} में`,`चंद्रमा ${SIGN_HI[moon.sign-1]} / भाव ${moon.house} में`,`नक्षत्र ${NAK_HI[moon.nakshatra.index-1]} पद ${moon.nakshatra.pada}`]);

  add("स्वभाव और निर्णय क्षमता",`${SIGN_LORD[lagna-1]} का भाव ${lagnaLord?.house||"—"} में होना बताता है कि जीवन के निर्णयों में ${h(lagnaLord?.house)} से जुड़े विषय बार-बार महत्वपूर्ण हो सकते हैं। ${lagnaLord?.retrograde?"वक्री लग्न स्वामी होने पर परंपरागत व्याख्या में निर्णय से पहले पुनर्विचार, समीक्षा और अनुभव से सीखने को महत्व दिया जाता है।":"लग्न स्वामी मार्गी होने पर निर्णयों में सीधी प्रगति और परिस्थितियों पर सक्रिय प्रतिक्रिया को महत्व दिया जाता है।"} निर्णय लेते समय भावनात्मक प्रतिक्रिया और व्यावहारिक लाभ के बीच संतुलन बनाए रखना उपयोगी रहेगा।`,`लग्न स्वामी की स्थिति और गति`,[`लग्न स्वामी: ${SIGN_LORD[lagna-1]}`,`स्थिति: भाव ${lagnaLord?.house||"—"}`,`राशि: ${lagnaLord?SIGN_HI[lagnaLord.sign-1]:"—"}`]);

  add("शिक्षा और ज्ञान",`पंचम भाव का स्वामी ${fifth.lord} भाव ${fifth.house||"—"} में है और बुध भाव ${merc.house} में स्थित है। पंचम भाव, बुध, गुरु और चंद्रमा को साथ देखकर पढ़ाई की शैली, स्मरण, तर्क, रचनात्मकता और विषय बदलने की प्रवृत्ति का पारंपरिक आकलन किया जाता है। गुरु भाव ${jup.house} में होने से ${[1,4,5,9,10,11].includes(jup.house)?"ज्ञान, उच्च अध्ययन, मार्गदर्शन और विशेषज्ञता विकसित करने के संकेतों को विशेष महत्व":"नियमित अभ्यास, सही शिक्षक और अनुशासन को शिक्षा के परिणामों में महत्वपूर्ण"} माना जाता है। तकनीकी, विश्लेषणात्मक, प्रबंधन, भाषा, सलाहकारी या ज्ञान-आधारित क्षेत्रों की उपयुक्तता को संबंधित ग्रहों और दशा से आगे जांचा जा सकता है।`,`पंचम स्वामी + बुध + गुरु + चंद्रमा`,[`पंचम स्वामी ${fifth.lord}: भाव ${fifth.house||"—"}`,`बुध: ${SIGN_HI[merc.sign-1]}, भाव ${merc.house}`,`गुरु: ${SIGN_HI[jup.sign-1]}, भाव ${jup.house}`]);

  add("करियर और व्यवसाय",`दशम भाव का स्वामी ${tenth.lord} भाव ${tenth.house||"—"} में है। दशम भाव, सूर्य, शनि और दशम स्वामी की स्थिति पेशेवर दिशा के मुख्य पारंपरिक संकेत हैं। ${[1,5,9,10,11].includes(tenth.house)?"दशम स्वामी का संबंध केंद्र/त्रिकोण/लाभ भाव से होने पर जिम्मेदारी, पहचान, पद या काम से उपलब्धि बनाने की प्रवृत्ति को महत्व दिया जाता है।":"करियर में स्थिरता बनाने के लिए कौशल-विकास, अनुभव और लगातार प्रयास को विशेष महत्व दिया जाता है।"} शनि भाव ${sat.house} में होने से दीर्घकालिक परिणामों में धैर्य और संरचना की भूमिका बढ़ती है। सूर्य भाव ${sun.house} में होने से नेतृत्व, अधिकार, आत्मविश्वास या वरिष्ठों से जुड़े विषय भी पेशेवर अनुभव में महत्वपूर्ण हो सकते हैं।`,`दशम भाव + दशम स्वामी + सूर्य + शनि`,[`दशम स्वामी ${tenth.lord}: भाव ${tenth.house||"—"}`,`सूर्य: भाव ${sun.house}`,`शनि: भाव ${sat.house}`,`स्थिति: ${houseStrength(tenth)}`]);

  add("धन, वित्त और आय",`धन के लिए द्वितीय भाव और उसका स्वामी ${second.lord}, आय के लिए एकादश भाव और उसका स्वामी ${eleventh.lord}, तथा वित्तीय विस्तार के लिए गुरु और सुख/भौतिक संसाधनों के लिए शुक्र को साथ देखा जाता है। द्वितीय स्वामी भाव ${second.house||"—"} तथा एकादश स्वामी भाव ${eleventh.house||"—"} में हैं। ${[1,2,5,9,10,11].includes(second.house)||[1,2,5,9,10,11].includes(eleventh.house)?"इनमें से कम-से-कम एक महत्वपूर्ण स्वामी लाभकारी भाव-संबंध में होने से कमाई और संसाधन बनाने की क्षमता के पारंपरिक संकेत मिलते हैं।":"आय और बचत में निरंतरता, बजट और जोखिम-नियंत्रण को विशेष महत्व देना चाहिए।"} वित्तीय परिणामों में दशा, गोचर और वास्तविक परिस्थितियां निर्णायक भूमिका निभाती हैं; इस भाग को निवेश की गारंटी न माना जाए।`,`द्वितीय/एकादश भाव + गुरु + शुक्र`,[`द्वितीय स्वामी ${second.lord}: भाव ${second.house||"—"}`,`एकादश स्वामी ${eleventh.lord}: भाव ${eleventh.house||"—"}`,`गुरु: भाव ${jup.house}`,`शुक्र: भाव ${venus.house}`]);

  add("विवाह और संबंध",`सप्तम भाव का स्वामी ${seventh.lord} भाव ${seventh.house||"—"} में है। सप्तम भाव, उसके स्वामी, शुक्र, चंद्रमा और D9/Navamsa को साथ देखकर संबंधों की प्रकृति और स्थिरता का पारंपरिक अध्ययन किया जाता है। ${[1,4,5,7,9,10,11].includes(seventh.house)?"सप्तम स्वामी का यह स्थान साझेदारी, सहयोग और संबंधों के विषय को जीवन में सक्रिय कर सकता है।":"संबंधों में स्पष्ट संवाद, धैर्य और अपेक्षाओं की स्पष्टता महत्वपूर्ण रहेगी।"} ${relationshipNote} यदि मंगल दोष या कोई अन्य screening match हुआ है तो उसे अकेले निर्णायक न मानकर cancellation factors तथा दोनों कुंडलियों के मिलान से देखना चाहिए।`,`सप्तम भाव + सप्तम स्वामी + शुक्र + चंद्रमा + D9`,[`सप्तम स्वामी ${seventh.lord}: भाव ${seventh.house||"—"}`,`शुक्र: भाव ${venus.house}`,`चंद्रमा: भाव ${moon.house}`,`मंगल दोष screening: ${doshaNames.includes("Mangal Dosha")?"Match":"No match"}`]);

  add("गृह, परिवार और संपत्ति",`चतुर्थ भाव का स्वामी ${fourth.lord} भाव ${fourth.house||"—"} में है। चतुर्थ भाव, चंद्रमा और शुक्र को घर, पारिवारिक सुख, वाहन, संपत्ति और मानसिक स्थिरता के पारंपरिक संकेतों के लिए देखा जाता है। ${[1,4,5,7,9,10,11].includes(fourth.house)?"यह स्थिति घर-परिवार और स्थिर संसाधनों को जीवन में महत्वपूर्ण बनाने का संकेत देती है।":"घर-परिवार से जुड़े निर्णयों में समय लेकर योजना बनाना और व्यावहारिक संतुलन रखना उपयोगी माना जाता है।"} संपत्ति के वास्तविक लेन-देन में कानूनी, वित्तीय और दस्तावेजी जांच अलग से आवश्यक है।`,`चतुर्थ भाव + चतुर्थ स्वामी + चंद्रमा + शुक्र`,[`चतुर्थ स्वामी ${fourth.lord}: भाव ${fourth.house||"—"}`,`चंद्रमा: भाव ${moon.house}`,`शुक्र: भाव ${venus.house}`]);

  add("संतान और रचनात्मकता",`पंचम भाव के स्वामी ${fifth.lord} की स्थिति, पंचम भाव में ग्रहों की उपस्थिति, गुरु और चंद्रमा को देखकर संतान, रचनात्मकता, बुद्धि और पूर्व पुण्य के पारंपरिक संकेतों का अध्ययन किया जाता है। पंचम स्वामी भाव ${fifth.house||"—"} में है और गुरु भाव ${jup.house} में है। ${[1,4,5,7,9,10,11].includes(fifth.house)?"इससे अध्ययन, रचनात्मक अभिव्यक्ति और ज्ञान को जीवन में उपयोग करने की प्रवृत्ति के संकेत मजबूत हो सकते हैं।":"इन क्षेत्रों में परिणामों के लिए निरंतर अभ्यास और उचित समय का महत्व अधिक रहेगा।"} संतान संबंधी किसी निश्चित परिणाम के लिए D7 और संबंधित दशा-गोचर की आवश्यकता होगी।`,`पंचम भाव + पंचम स्वामी + गुरु`,[`पंचम स्वामी ${fifth.lord}: भाव ${fifth.house||"—"}`,`गुरु: भाव ${jup.house}`,`D7: अभी इस build में पूर्ण rule-set सक्रिय नहीं है`]);

  add("भाग्य, धर्म और उच्च अध्ययन",`नवम भाव के स्वामी ${ninth.lord} भाव ${ninth.house||"—"} में हैं। नवम भाव से उच्च शिक्षा, गुरु/मार्गदर्शन, लंबी यात्रा, दर्शन और जीवन-दृष्टि के संकेत देखे जाते हैं। ${[1,5,9,10,11].includes(ninth.house)?"नवम स्वामी का संबंध लाभकारी भावों से होने पर मार्गदर्शन, उच्च अध्ययन और अवसरों के विषय सक्रिय रहने की पारंपरिक व्याख्या की जाती है।":"भाग्य से जुड़े परिणामों में व्यक्तिगत प्रयास, सही लोगों का मार्गदर्शन और समय का महत्व अधिक रहेगा।"} दूर की यात्रा या विदेश के लिए नवम के साथ द्वादश भाव और राहु को भी देखना चाहिए।`,`नवम भाव + नवम स्वामी + गुरु`,[`नवम स्वामी ${ninth.lord}: भाव ${ninth.house||"—"}`,`गुरु: भाव ${jup.house}`,`नवम भाव का विषय: भाग्य/धर्म/उच्च अध्ययन`]);

  add("विदेश, यात्रा और स्थान परिवर्तन",`नवम और द्वादश भाव, उनके स्वामी, राहु तथा संबंधित दशा-गोचर को विदेश, दूरस्थ स्थान और लंबी यात्रा के पारंपरिक संकेतों में देखा जाता है। द्वादश स्वामी ${twelfth.lord} भाव ${twelfth.house||"—"} में है और राहु भाव ${planets.Rahu.house} में है। ${[3,9,12].includes(twelfth.house)||[3,9,12].includes(planets.Rahu.house)?"यात्रा/स्थान परिवर्तन से जुड़े संकेतों को अधिक सक्रिय मानने का आधार मिलता है।":"विदेश या लंबी यात्रा का परिणाम मुख्यतः दशा-गोचर और वास्तविक अवसरों से जुड़ा रहेगा।"} किसी विशेष वर्ष या महीने की timing के लिए वर्तमान दशा और गोचर का अलग विश्लेषण आवश्यक है।`,`नवम/द्वादश भाव + राहु + दशा`,[`द्वादश स्वामी ${twelfth.lord}: भाव ${twelfth.house||"—"}`,`राहु: भाव ${planets.Rahu.house}`,`नवम स्वामी ${ninth.lord}: भाव ${ninth.house||"—"}`]);

  add("स्वास्थ्य और जीवनशैली संकेत",`छठे, आठवें और बारहवें भाव तथा उनके स्वामियों को पारंपरिक ज्योतिष में स्वास्थ्य, तनाव, दिनचर्या और कठिन परिस्थितियों के संकेतों के लिए देखा जाता है। छठे स्वामी ${sixth.lord} भाव ${sixth.house||"—"}, आठवें स्वामी ${eighth.lord} भाव ${eighth.house||"—"} और द्वादश स्वामी ${twelfth.lord} भाव ${twelfth.house||"—"} में हैं। इससे दिनचर्या, नींद, काम का दबाव और नियमित देखभाल जैसे विषयों को संतुलित रखना उपयोगी माना जा सकता है। यह ज्योतिषीय व्याख्या है—किसी रोग का निदान, भविष्यवाणी या उपचार-सलाह नहीं।`,`छठा/आठवां/बारहवां भाव`,[`छठा स्वामी ${sixth.lord}: भाव ${sixth.house||"—"}`,`आठवां स्वामी ${eighth.lord}: भाव ${eighth.house||"—"}`,`बारहवां स्वामी ${twelfth.lord}: भाव ${twelfth.house||"—"}`]);

  const yogaPhalMap={
    "Budhaditya Yoga":()=>`बुधादित्य योग के कारण बुद्धि, तर्क, सीखने, लेखन/वाणी, गणना और निर्णय क्षमता से जुड़े विषयों में पारंपरिक रूप से सहयोग माना जाता है। सूर्य भाव ${sun.house} और बुध भाव ${merc.house} में होने से इसका फल करियर, शिक्षा और संचार के क्षेत्रों में अधिक दिखाई दे सकता है। बुध की स्थिति और सूर्य से निकटता के कारण फल की तीव्रता बदल सकती है।`,
    "Gajakesari Yoga":()=>`गजकेसरी योग चंद्रमा और गुरु के केंद्र संबंध से बना है। पारंपरिक फलादेश में ज्ञान, मार्गदर्शन, प्रतिष्ठा, निर्णय क्षमता, संरक्षण और अवसरों को बढ़ाने वाला संकेत माना जाता है। चंद्रमा भाव ${moon.house} तथा गुरु भाव ${jup.house} में होने से मन, शिक्षा, सलाह और सामाजिक/पेशेवर विकास में इसका प्रभाव देखा जाता है।`,
    "Chandra-Mangala Yoga":()=>`चंद्र-मंगल योग धन-प्रबंधन, व्यापारिक पहल, कार्य-ऊर्जा और संसाधनों को सक्रिय करने वाला पारंपरिक योग माना जाता है। चंद्रमा और मंगल की युति भाव ${moon.house} में होने से कमाई के अवसरों के साथ भावनात्मक निर्णय या जल्दबाजी को भी संतुलित करना महत्वपूर्ण हो सकता है।`,
    "Ruchaka Mahapurusha Yoga":()=>`रुचक महापुरुष योग मंगल के केंद्र में स्व/उच्च राशि में होने से साहस, नेतृत्व, प्रतिस्पर्धा, तकनीकी क्षमता और निर्णायक कार्यशक्ति से जोड़ा जाता है। मंगल भाव ${mars.house} और राशि ${SIGN_HI[mars.sign-1]} में है; इसलिए इसके फल को दशा और मंगल के अन्य संबंधों के साथ पढ़ना चाहिए।`,
    "Bhadra Mahapurusha Yoga":()=>`भद्र महापुरुष योग बुध के केंद्र में स्व/उच्च राशि में होने से बुद्धि, विश्लेषण, व्यापार, संचार, गणना और रणनीतिक सोच के पारंपरिक संकेत देता है। बुध भाव ${merc.house} में है, इसलिए शिक्षा और करियर में इसकी भूमिका विशेष रूप से देखी जाती है।`,
    "Hamsa Mahapurusha Yoga":()=>`हंस महापुरुष योग गुरु के केंद्र में स्व/उच्च राशि में होने से ज्ञान, शिक्षा, सलाह, धर्म, नैतिकता और संरक्षण के पारंपरिक संकेतों से जुड़ा माना जाता है। गुरु भाव ${jup.house} में है; इसका वास्तविक फल गुरु की दशा, दृष्टि और नवांश स्थिति से बदल सकता है।`,
    "Malavya Mahapurusha Yoga":()=>`मालव्य महापुरुष योग शुक्र के केंद्र में स्व/उच्च राशि में होने से कला, आकर्षण, सुविधा, संबंध, वाहन/संपत्ति और भौतिक संसाधनों के पारंपरिक संकेतों से जोड़ा जाता है। शुक्र भाव ${venus.house} में है; संबंध और वित्तीय फल को शुक्र की दशा तथा अन्य ग्रह-संबंधों के साथ पढ़ना चाहिए।`,
    "Sasa Mahapurusha Yoga":()=>`शश महापुरुष योग शनि के केंद्र में स्व/उच्च राशि में होने से अनुशासन, संगठन, प्रशासन, दीर्घकालिक उपलब्धि और जिम्मेदारी के पारंपरिक संकेत देता है। शनि भाव ${sat.house} में है; फल सामान्यतः समय के साथ विकसित होने वाला माना जाता है।`,
    "Dharma-Karmadhipati Yoga":()=>`धर्म-कर्माधिपति योग नवम और दशम भाव के स्वामियों के संबंध से बनता है। पारंपरिक फलादेश में भाग्य, मार्गदर्शन, उच्च अध्ययन, करियर, पद और उद्देश्यपूर्ण कर्म के बीच संबंध का संकेत माना जाता है। नवम स्वामी ${ninth.lord} और दशम स्वामी ${tenth.lord} का संबंध होने से शिक्षा/मार्गदर्शन को करियर दिशा से जोड़कर पढ़ा जाता है।`,
    "Dhana Yoga Screening":()=>`धन योग screening में धन/पंचम/नवम भाव के स्वामियों का लाभकारी भावों से संबंध मिला है। पारंपरिक फलादेश में आय, बचत, संसाधन निर्माण और अवसरों से आर्थिक लाभ के संकेत देखे जाते हैं। इसका फल संबंधित ग्रहों की दशा, बल और द्वितीय/एकादश भाव की स्थिति पर निर्भर करता है।`
  };
  const doshaPhalMap={
    "Mangal Dosha":()=>`मंगल दोष screening में मंगल का मंगलिक भावों से संबंध मिला है। पारंपरिक ज्योतिष में इसे वैवाहिक जीवन में तीव्रता, मतभेद या अपेक्षाओं के असंतुलन से जोड़कर देखा जाता है, लेकिन इसे अकेले विवाह-विच्छेद या निश्चित अशुभ घटना का कारण नहीं माना जाना चाहिए। मंगल भाव ${mars.house} में है। चंद्र, शुक्र, सप्तम भाव/स्वामी, नवांश, दोनों पक्षों की कुंडली और cancellation factors को साथ देखना आवश्यक है।`,
    "Surya Grahan Dosha":()=>`सूर्य-ग्रहण दोष screening में सूर्य का राहु/केतु से संबंध मिला है। पारंपरिक फलादेश में आत्मविश्वास, पिता/अधिकार, प्रतिष्ठा और निर्णय क्षमता से जुड़े क्षेत्रों में उतार-चढ़ाव का संकेत माना जाता है। सूर्य भाव ${sun.house} में है; फल सूर्य की शक्ति, दूरी, दृष्टि और दशा के अनुसार बदलता है।`,
    "Chandra Grahan Dosha":()=>`चंद्र-ग्रहण दोष screening में चंद्रमा का राहु/केतु से संबंध मिला है। पारंपरिक फलादेश में मन, भावनात्मक स्थिरता, निर्णय और मानसिक दबाव से जुड़े विषयों को सावधानी से देखने की सलाह दी जाती है। चंद्रमा भाव ${moon.house} में है; पूर्ण निष्कर्ष के लिए चंद्रबल, नवांश और दशा देखना आवश्यक है।`,
    "Papakartari/Chandra Affliction Screening":()=>`चंद्रमा के साथ प्राकृतिक पाप ग्रह का संबंध मिला है। पारंपरिक व्याख्या में इससे मन की चिंता, भावनात्मक दबाव या परिस्थितियों के प्रति तीखी प्रतिक्रिया जैसे संकेत जोड़े जाते हैं। यहां यह केवल screening है; वास्तविक Papakartari के लिए चंद्रमा के दोनों ओर के भावों की पूर्ण जांच अलग से आवश्यक है।`,
    "Mars Debilitation":()=>`मंगल कर्क राशि में होने के कारण पारंपरिक रूप से नीच माना गया है। इससे ऊर्जा, साहस, क्रोध, निर्णय और कार्यान्वयन के विषयों में असंतुलन का संकेत माना जा सकता है। लेकिन नीचभंग, दृष्टि, युति, नवांश और दशा जैसे factors परिणाम को काफी बदल सकते हैं।`,
    "Saturn Debilitation":()=>`शनि मेष राशि में होने के कारण पारंपरिक रूप से नीच माना गया है। अनुशासन, धैर्य, जिम्मेदारी और दीर्घकालिक कार्यों में अतिरिक्त प्रयास की पारंपरिक व्याख्या की जाती है। नीचभंग और शनि के अन्य बलों की जांच आवश्यक है।`,
    "Jupiter Debilitation":()=>`गुरु मकर राशि में होने के कारण पारंपरिक रूप से नीच माना गया है। शिक्षा, मार्गदर्शन, विश्वास, वित्तीय विवेक या विस्तार के विषयों में परिणाम परिस्थिति और दशा के अनुसार बदल सकते हैं। नीचभंग, दृष्टि और नवांश देखना आवश्यक है।`,
    "Venus Debilitation":()=>`शुक्र कन्या राशि में होने के कारण पारंपरिक रूप से नीच माना गया है। संबंध, सुविधा, कला और वित्तीय पसंद में अधिक विश्लेषण या अपेक्षाओं की प्रवृत्ति की पारंपरिक व्याख्या की जाती है। नीचभंग, युति, दृष्टि और दशा से परिणाम बदल सकते हैं।`
  };
  if(yogaNames.length){
    data.yogas.forEach(y=>{
      const fn=yogaPhalMap[y.name]||(()=>`${y.name} इस कुंडली में detected है। ${y.basis||"Rule match"} इसके गठन का आधार है। इसका पारंपरिक फल संबंधित ग्रहों की राशि, भाव, बल, दृष्टि, नवांश और दशा के अनुसार बदलता है।`);
      add(`शुभ योग फल — ${y.name}`,fn(),`Detected Yoga: ${y.name}`,[`गठन: ${y.basis}`,`स्थिति: ${y.strength||"Rule match"}`,`स्थिति की जांच: संबंधित ग्रहों के भाव, राशि, बल, D9 और दशा`]);
    });
  } else add("शुभ योग फल","इस कुंडली में उपलब्ध configured शुभ योग rules में कोई detected match नहीं मिला। इसलिए केवल इस section में कोई योग-विशेष फल नहीं जोड़ा गया है। अन्य सामान्य सकारात्मक फलादेश अलग chart factors से आता है।","No detected Shubh Yoga",["उपलब्ध yoga rules checked: "+(data.ruleSummary?.yogaRulesChecked||0)]);

  if(doshaNames.length){
    data.doshas.forEach(d=>{
      const fn=doshaPhalMap[d.name]||(()=>`${d.name} इस कुंडली में detected है। ${d.basis||"Rule match"} इसका screening आधार है। इसका पारंपरिक प्रभाव संबंधित ग्रह, भाव, राशि, D9, cancellation factors और दशा के अनुसार बदलता है।`);
      add(`अशुभ योग / दोष फल — ${d.name}`,fn(),`Detected Dosha: ${d.name}`,[`गठन: ${d.basis}`,`Severity/context: ${d.severity||"Context dependent"}`,`निष्कर्ष से पहले ग्रहबल, cancellation, D9 और दशा जांचें`]);
    });
  } else add("अशुभ योग / दोष फल","इस कुंडली में उपलब्ध configured अशुभ योग/दोष rules में कोई detected match नहीं मिला। इसलिए कोई दोष-विशेष फल नहीं जोड़ा गया है। सामान्य चुनौतियां अन्य भाव और ग्रह स्थिति से अलग पढ़ी जाती हैं।","No detected Ashubh Yoga/Dosha",["उपलब्ध dosha rules checked: "+(data.ruleSummary?.doshaRulesChecked||0)]);

  if(currentMd) add("वर्तमान महादशा",`वर्तमान तिथि के आधार पर ${currentMd.lord} की महादशा ${currentMd.start} से ${currentMd.end} तक चल रही है। इस अवधि का फलादेश ${currentMd.lord} के जन्मकुंडली में भाव, राशि, स्वामित्व, नक्षत्र, D9 स्थिति और साथ चल रही अंतर्दशा के अनुसार बदलता है। इसलिए केवल महादशा ग्रह का नाम देखकर अच्छा या बुरा परिणाम तय नहीं किया गया है।`,`वर्तमान महादशा + ग्रह की जन्म स्थिति`,[`महादशा: ${currentMd.lord}`,`अवधि: ${currentMd.start} → ${currentMd.end}`,`जन्म स्थिति: भाव ${planets[currentMd.lord]?.house||"—"}, राशि ${planets[currentMd.lord]?SIGN_HI[planets[currentMd.lord].sign-1]:"—"}`]);

  add("धन-संपत्ति और खर्च का संतुलन",`द्वितीय और एकादश भाव कमाई/संचय की दिशा बताते हैं जबकि द्वादश भाव खर्च और संसाधनों के बाहर जाने की परंपरागत दिशा बताता है। इस कुंडली में द्वितीय स्वामी ${second.lord} भाव ${second.house||"—"}, एकादश स्वामी ${eleventh.lord} भाव ${eleventh.house||"—"} और द्वादश स्वामी ${twelfth.lord} भाव ${twelfth.house||"—"} में हैं। इसलिए आय बढ़ाने के साथ बचत-व्यवस्था और अनावश्यक खर्च पर नियंत्रण को भी फलादेश का महत्वपूर्ण भाग माना जाना चाहिए। वित्तीय निर्णयों में वास्तविक आय, देनदारी, जोखिम और कानूनी/कर नियमों को प्राथमिक आधार रखें।`,`2nd + 11th + 12th house synthesis`,[`2nd lord: ${second.lord} / H${second.house||"—"}`,`11th lord: ${eleventh.lord} / H${eleventh.house||"—"}`,`12th lord: ${twelfth.lord} / H${twelfth.house||"—"}`]);

  add("मुख्य शक्तियां और ध्यान देने योग्य क्षेत्र",`इस chart में केंद्र भावों में पारंपरिक शुभ ग्रहों की उपस्थिति/स्थिति ${kendraCount} महत्वपूर्ण स्थानों तक पहुंचती है, जबकि चुनौती वाले भावों में configured natural malefic placements की संख्या ${dusthanaCount} है। इसे numerical score या निश्चित भाग्य-रेटिंग नहीं माना जाता; यह केवल यह बताने के लिए है कि फलादेश में किन क्षेत्रों को साथ देखकर पढ़ा गया। मुख्य सकारात्मक दिशा ज्ञान, कौशल, संबंधों में स्पष्टता और दीर्घकालिक प्रयास हो सकती है; ध्यान देने योग्य क्षेत्र खर्च, तनाव, जल्दबाजी या संबंधों में अपेक्षाओं की स्पष्टता जैसे विषय हो सकते हैं।`,`सहायक और चुनौतीपूर्ण भावों का संयुक्त अवलोकन`,[`केंद्रों में चुने गए शुभ ग्रह: ${kendraCount}`,`दुष्ट भावों में चुने गए प्राकृतिक पाप ग्रह: ${dusthanaCount}`,`अलग से योग/दोष rules भी जांचे गए हैं`]);

  add("समग्र विस्तृत फलादेश",`कुल मिलाकर ${SIGN_HI[lagna-1]} लग्न, ${SIGN_HI[moon.sign-1]} राशि और ${NAK_HI[moon.nakshatra.index-1]} नक्षत्र वाली यह कुंडली जीवन को एक ही क्षेत्र से नहीं बल्कि व्यक्तित्व, शिक्षा, करियर, धन, संबंध, परिवार, यात्रा और आध्यात्मिक/उच्च अध्ययन के संयुक्त ढांचे से देखने की जरूरत बताती है। लग्न स्वामी भाव ${lagnaLord?.house||"—"}, दशम स्वामी भाव ${tenth.house||"—"}, द्वितीय स्वामी भाव ${second.house||"—"} और एकादश स्वामी भाव ${eleventh.house||"—"} में होने से जीवन के निर्णयों में आत्म-विकास, काम और संसाधन-प्रबंधन के विषय महत्वपूर्ण रहेंगे। समय-विशेष की घटनाओं के लिए दशा-अंतर्दशा-प्रत्यंतर और गोचर को संबंधित भावों के साथ जोड़ना आवश्यक है।`,`सभी मुख्य भाव + Dasha + Yoga/Dosha का synthesis`,[`लग्न: ${SIGN_HI[lagna-1]}`,`राशि: ${SIGN_HI[moon.sign-1]}`,`करियर स्वामी: ${tenth.lord} / H${tenth.house||"—"}`,`धन स्वामी: ${second.lord} / H${second.house||"—"}`,`लाभ स्वामी: ${eleventh.lord} / H${eleventh.house||"—"}`]);

  return {summary:`${SIGN_HI[lagna-1]} लग्न, ${SIGN_HI[moon.sign-1]} राशि और ${NAK_HI[moon.nakshatra.index-1]} नक्षत्र के आधार पर विस्तृत जन्म फलादेश। Finance, Education, Career, Personality, Marriage, Family, Travel, Health-signals, Yoga/Dosha और Dasha सभी को अलग-अलग chart factors के साथ समझाया गया है।`,points:items,note:"यह पारंपरिक वैदिक ज्योतिषीय व्याख्या है, निश्चित या वैज्ञानिक भविष्यवाणी नहीं। स्वास्थ्य, वित्त, विवाह या अन्य महत्वपूर्ण निर्णयों के लिए वास्तविक परिस्थितियों और योग्य पेशेवर सलाह को प्राथमिकता दें।"};
}
function makeUnsupportedVarga(name){return{supported:false,name,note:'Traditional Parashari/Jaimini rule set for this varga is not enabled yet.'}}
async function calculateKundli(input){const provider=await calculateEphemeris(input),asc=Number(provider.houses.ascendant),lagna=sign(asc),planets={};for(const p of PLANETS){const z=provider.planets[p],s=sign(z.longitude);planets[p]={name:p,longitude:+Number(z.longitude).toFixed(6),degreeInSign:degreeInSign(z.longitude),degreeDms:degToDms(degreeInSign(z.longitude)),latitude:+Number(z.latitude||0).toFixed(6),speed:+Number(z.speed||0).toFixed(8),retrograde:Number(z.speed||0)<0,sign:s,signName:SIGNS[s-1],signEnglish:SIGN_EN[s-1],house:houseFromAsc(asc,z.longitude),nakshatra:nakshatra(z.longitude),d9Sign:navamsaSign(z.longitude)}}const d1=buildD1(asc,planets),d9=buildD9(asc,planets),charts={D1:d1,D9:d9};for(const n of ['D2','D3','D4','D5','D6','D7','D8','D10','D11','D12','D16','D20','D24','D27','D30','D40','D45','D60'])charts[n]=makeUnsupportedVarga(n);const rules=yogaRules(planets,lagna);const details=birthDetails(input,provider,asc,lagna,planets);const dasha=dashas(provider.planets.Moon.longitude,input);const phala=phalaDesh({...details,...rules,dasha},planets,lagna);return{input,ayanamsa:'Lahiri',lagna:{longitude:+asc.toFixed(6),degreeInSign:degreeInSign(asc),degreeDms:degToDms(degreeInSign(asc)),sign:lagna,signName:SIGNS[lagna-1],signEnglish:SIGN_EN[lagna-1]},planets,charts,dasha,birthDetails:details,phalaDesh:phala,...rules,engine:{name:'Bhavishya Gyani Astrology Engine V9',provider:provider.provider|| (provider.fallback?'built-in-sidereal-astronomy':'local-swiss-ephemeris'),productionRequired:true,accuracyNote:'Production calculation requires Swiss Ephemeris. Vercel uses the dedicated Python Swiss Ephemeris function; local development uses the same pyswisseph bridge. The low-precision fallback is retained only for local diagnostics and is never silently used on Vercel.'}}}
module.exports={calculateKundli,SIGNS,NAK,navamsaSign};
